{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stpphawkes
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stpphawkes_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stpphawkes/stpphawkes_{{ version }}.tar.gz
  sha256: cc661246f2434843418ec5977d04dae8c9984635e2613e66de98fe2ae2a869d2

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'                    # [win]
    - '*/Rblas.dll'                # [win]
    - '*/Rlapack.dll'              # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcpparmadillo              # [build_platform != target_platform]
    - r-rcppgsl                    # [build_platform != target_platform]
    - r-rcppprogress               # [build_platform != target_platform]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppgsl
    - r-rcppprogress
    - r-extradistr
    - r-interp
    - libblas
    - liblapack
    - libgomp                      # [not osx]
    - gsl
    - llvm-openmp
  run:
    - libgomp                      # [win]
    - r-base
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppgsl
    - r-rcppprogress
    - r-extradistr
    - r-interp
    - libblas
    - liblapack
    - gsl
    - llvm-openmp

test:
  commands:
    - $R -e "library('stpphawkes')"           # [not win]
    - "\"%R%\" -e \"library('stpphawkes')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=stpphawkes
  license: MIT
  summary: Estimation of model parameters for marked Hawkes process. Accounts for missing data in the estimation of the parameters. Technical details found in (Tucker et al., 2019 <DOI:10.1016/j.spasta.2018.12.004>).
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - jdtuck

# Package: stpphawkes
# Type: Package
# Title: Missing Data for Marked Hawkes Process
# Version: 0.2.1
# Date: 2023-08-13
# Authors@R: c( person("J. Derek", "Tucker", email = "jdtuck@sandia.gov", role = c("aut","cre")), person("Lyndsay", "Shand", email = "lshand@sandia.gov", role = "aut"), person("Stephen", "Rowe", email = "srowe@sandia.gov", role = "aut"), person("John", "Lewis", email = "jrlewi@sandia.gov", role = "aut"))
# Description: Estimation of model parameters for marked Hawkes process. Accounts for missing data in the estimation of the parameters. Technical details found in (Tucker et al., 2019 <DOI:10.1016/j.spasta.2018.12.004>).
# Imports: interp, extraDistr, Rcpp
# License: MIT + file LICENSE
# Encoding: UTF-8
# SystemRequirements: GNU GSL
# NeedsCompilation: yes
# LinkingTo: Rcpp, RcppArmadillo, RcppProgress, RcppGSL
# RoxygenNote: 7.2.3
# Packaged: 2023-08-14 13:16:00 UTC; jdtuck
# Author: J. Derek Tucker [aut, cre], Lyndsay Shand [aut], Stephen Rowe [aut], John Lewis [aut]
# Maintainer: J. Derek Tucker <jdtuck@sandia.gov>
# Repository: CRAN
# Date/Publication: 2023-08-15 17:10:02 UTC
